server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    # Proxy API + uploaded media to backend
    location /api {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /uploads-book-reviewer/ {
        proxy_pass http://app:8080/uploads-book-reviewer/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /avatars/ {
        proxy_pass http://app:8080/avatars/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}