-- Seed catalog books (+ genres) for fresh installs.
-- Skips when books already exist so local/dev DBs with data are not duplicated.

DO $seed$
BEGIN
  IF EXISTS (SELECT 1 FROM public.books LIMIT 1) THEN
    RAISE NOTICE 'Skipping V2 book seed: books table is not empty';
    RETURN;
  END IF;

  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (13, 'F. Scott Fitzgerald', 0, 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1401238257i/396094.jpg', '2026-04-23 13:23:33.275348', 'In the opulent haze of the Roaring Twenties, the mysterious Jay Gatsby throws lavish parties in his Long Island mansion, hoping to attract the attention of his lost love, Daisy Buchanan. Narrated by the disillusioned Nick Carraway, the story exposes the glittering surface of wealth and the hollow despair beneath. Fitzgerald’s masterpiece is a lyrical, devastating portrait of the American Dream—its promise, its corruption, and its ultimate impossibility.', 'the great gatsby', 1925, 0, 'The Great Gatsby', 0, 'f scott fitzgerald', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (3, 'Donna Tartt', 5, 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1751820530i/29044.jpg', '2026-04-18 12:05:09.141175', 'Under the influence of their charismatic classics professor, a group of clever, eccentric misfits at an elite New England college discover a way of thinking and living that is a world away from the humdrum existence of their contemporaries. But when they go beyond the boundaries of normal morality they slip gradually from obsession to corruption and betrayal, and at last—inexorably—into evil.', 'the secret history', 1992, 3, 'The Secret History', 3, 'donna tartt', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (5, 'Walter Tevis', 4, 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1667838766i/55849740.jpg', '2026-04-18 20:34:03.610482', 'Eight-year-old orphan Beth Harmon is quiet, sullen, and unremarkable—until she plays her first game of chess. Her senses grow sharper, her thinking clearer, and for the first time in her life she feels herself fully in control. By the age of sixteen, she is competing for the U.S. Open championship. But as she hones her skills on the professional circuit, the stakes rise, her isolation grows, and the thought of escape becomes all the more tempting. A gripping portrait of genius, addiction, and the cost of survival.', 'the queens gambit', 1983, 1, 'The Queen''s Gambit', 1, 'walter tevis', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (7, 'Albert Camus', 0, 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1738704267i/49552.jpg', '2026-04-21 12:11:44.454279', 'Meursault, a French Algerian, drifts through life with an almost eerie detachment. When his mother dies, he feels no grief. When he becomes entangled in a violent confrontation on a sun-drenched beach, he kills a man with no apparent motive. During his trial, society condemns him not for the murder itself, but for his refusal to conform to expected emotional norms—his failure to cry at his mother''s funeral becomes a damning indictment. Through Meursault''s story, Camus explores the absurdity of existence, the indifference of the universe, and the quiet rebellion of living authentically in a world that demands we perform meaning.', 'the stranger', 1942, 0, 'The Stranger', 0, 'albert camus', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (4, 'Ray Bradbury', 4.666666666666667, 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1374049845i/50033.jpg', '2026-04-18 20:25:09.410344', 'The summer of ''28 was a vintage season for a growing boy. A summer of green apple trees, mowed lawns, and new sneakers. Of half-burnt firecrackers, of gathering dandelions, of Grandma''s belly-busting dinner. It was a summer of sorrows and marvels and gold-fuzzed bees. A magical, timeless summer in the life of a twelve-year-old boy named Douglas Spaulding—remembered forever by the incomparable Ray Bradbury.', 'dandelion wine', 1957, 3, 'Dandelion Wine', 3, 'ray bradbury', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (8, 'Mary Shelley', 4, 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1631088473i/35031085.jpg', '2026-04-21 12:12:23.990691', 'Obsessed with discovering the secret of life, young scientist Victor Frankenstein assembles a creature from body parts and brings it to life through a mysterious spark. But horrified by his own creation, he abandons the being, setting into motion a tragic chain of revenge and despair. The creature, intelligent and sensitive, is shunned by humanity solely for its monstrous appearance. What follows is a harrowing chase across frozen wastes and a profound meditation on creation, responsibility, isolation, and what it truly means to be human. Mary Shelley''s masterpiece gave birth to both science fiction and the modern horror genre, yet its deepest terrors lie not in the supernatural, but in the all-too-human failures of empathy and accountability.', 'frankenstein', 1818, 1, 'Frankenstein', 1, 'mary shelley', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (6, 'R.F. Kuang', 5, 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1677361825i/57945316.jpg', '2026-04-21 12:11:00.766816', '1828. Robin Swift, orphaned by cholera in Canton, is brought to London by the mysterious Professor Lovell. There, he trains for years in Latin, Ancient Greek, and Chinese, all in preparation for the day he''ll enroll in Oxford University''s prestigious Royal Institute of Translation—also known as Babel. Babel is the world''s center for translation and, more importantly, magic. Silver-working—the art of manifesting the meaning lost in translation using enchanted silver bars—has made the British Empire unparalleled in power. But Robin soon discovers that serving Babel means betraying his homeland, and as his studies progress, he finds himself caught between his duty to the Institute, his loyalty to his friends, and the growing anti-imperialist resistance movement. A sweeping, dark academic fantasy that grapples with language, colonialism, and the cost of revolution.', 'babel', 2022, 1, 'Babel', 1, 'r.f. kuang', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (14, 'Charlotte Brontë', 0, 'https://m.media-amazon.com/images/I/81pwJjgcwwL._AC_UF894,1000_QL80_.jpg', '2026-04-24 20:26:26.98674', 'Orphaned as a child and raised by cold, unloving relatives, Jane Eyre grows into a woman of fierce independence and quiet strength. As a governess at the mysterious Thornfield Hall, she falls in love with her brooding employer, Mr. Rochester, only to discover a shocking secret that forces her to choose between love and self-respect. More than a romance, ''Jane Eyre'' is a revolutionary exploration of morality, class, gender, and the struggle for personal freedom. Brontë’s novel broke literary ground by giving voice to an ordinary woman’s interior life with unprecedented psychological depth and fiery passion.', 'jane eyre', 1847, 0, 'Jane Eyre', 0, 'charlotte brontë', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (16, 'Suzanne Collins', 0, '/images/book-covers/the-hunger-games.jpg', '2026-09-16 18:39:39.080492', 'In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV. Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister''s place in the Games. But Katniss has been close to dead before - and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weigh survival against humanity and life against love. A gripping, action-packed dystopian novel that launched a worldwide phenomenon and grapples with inequality, rebellion, and the cost of survival.', 'the hunger games', 1994, 0, 'The Hunger Games', 0, 'suzanne collins', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (17, 'George Orwell', 0, '/images/book-covers/1984.jpg', '2026-09-19 00:00:19.602823', 'In a world divided into three superstates, Oceania is ruled by the Party and its omnipresent leader, Big Brother. Every thought, word, and action is monitored, history is rewritten, and language itself is stripped down to make dissent impossible. Winston Smith, a minor clerk at the Ministry of Truth, spends his days destroying inconvenient records - until he begins secretly questioning the regime. When he starts a forbidden affair with Julia and dares to imagine rebellion, he is drawn into a dangerous web of surveillance, betrayal, and torture. A chilling, prophetic dystopia about totalitarianism, truth, and the terrifying cost of freedom.', '1984', 1949, 0, '1984', 0, 'george orwell', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (18, 'Aldous Huxley', 0, '/images/book-covers/brave-new-world.jpg', '2026-09-19 00:03:01.631305', 'In a future World State, citizens are engineered in bottles, conditioned from birth, and sorted into castes designed to keep society stable. Happiness is mandatory, promiscuity is encouraged, and any hint of discontent is smoothed over with the drug soma. Bernard Marx, an Alpha who feels out of place, and Lenina Crowne, who longs for something more, visit a Savage Reservation - and return with John, a man raised outside the World State’s carefully managed pleasures. As John struggles to reconcile his old-world morality with a society that has abolished pain, family, and art, his presence threatens to expose the emptiness beneath utopia. A provocative, prescient novel about technology, conformity, and the price of comfort.', 'brave new world', 1932, 0, 'Brave New World', 0, 'aldous huxley', NULL);
  INSERT INTO public.books (id, author, average_rating, cover_url, created_at, description, normalized_title, publication_year, rating_count, title, total_reviews, normalized_author, pacing) VALUES (19, 'M.L. Rio', 5, '/images/book-covers/if-we-were-villains.jpg', '2026-09-19 00:10:50.814318', 'On the day Oliver Marks is released from jail, the man who put him there is waiting at the door. Detective Colborne wants to know the truth, and after ten years, Oliver is finally ready to tell it.
  A decade earlier, Oliver was one of seven young Shakespearean actors at Dellecher Classical Conservatory, a place of keen ambition and fierce competition. In this secluded world of firelight and leather-bound books, Oliver and his friends played the same roles onstage and off: hero, villain, tyrant, temptress, ingénue, extras. But in their fourth and final year, good-natured rivalries turned ugly, and on opening night real violence invaded the students'' world of make-believe. In the morning, the fourth-years found themselves facing their very own tragedy, and their greatest acting challenge yet: convincing the police, each other, and themselves that they are innocent.
  A dark, atmospheric debut that blends Shakespearean drama with a gripping murder mystery, exploring love, obsession, and the dangerous line between performance and reality', 'if we were villains', 2017, 1, 'If We Were Villains', 1, 'ml rio', NULL);
  INSERT INTO public.book_genres (book_id, genre) VALUES (3, 'Mystery');
  INSERT INTO public.book_genres (book_id, genre) VALUES (3, 'Detective');
  INSERT INTO public.book_genres (book_id, genre) VALUES (3, 'Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (4, 'Classics');
  INSERT INTO public.book_genres (book_id, genre) VALUES (4, 'Magical Realism');
  INSERT INTO public.book_genres (book_id, genre) VALUES (4, 'Coming of Age');
  INSERT INTO public.book_genres (book_id, genre) VALUES (4, 'Science Fiction Fantasy');
  INSERT INTO public.book_genres (book_id, genre) VALUES (4, 'Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (5, 'Historical Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (5, 'Literary Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (5, 'Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (5, 'Sports');
  INSERT INTO public.book_genres (book_id, genre) VALUES (6, 'Historical Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (6, 'Literary Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (6, 'Fantasy');
  INSERT INTO public.book_genres (book_id, genre) VALUES (6, 'Dark Academia');
  INSERT INTO public.book_genres (book_id, genre) VALUES (7, 'Classics');
  INSERT INTO public.book_genres (book_id, genre) VALUES (7, 'Literary Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (7, 'Absurdist Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (7, 'Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (7, 'Philosophy');
  INSERT INTO public.book_genres (book_id, genre) VALUES (8, 'Classics');
  INSERT INTO public.book_genres (book_id, genre) VALUES (8, 'Horror');
  INSERT INTO public.book_genres (book_id, genre) VALUES (8, 'Literary Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (8, 'Gothic');
  INSERT INTO public.book_genres (book_id, genre) VALUES (8, 'Science Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (13, 'Classics');
  INSERT INTO public.book_genres (book_id, genre) VALUES (13, 'Historical Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (14, 'Classics');
  INSERT INTO public.book_genres (book_id, genre) VALUES (14, 'Historical Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (16, 'Adventure');
  INSERT INTO public.book_genres (book_id, genre) VALUES (16, 'Dystopian');
  INSERT INTO public.book_genres (book_id, genre) VALUES (16, 'Science Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (13, 'Literary Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (17, 'Dystopian');
  INSERT INTO public.book_genres (book_id, genre) VALUES (17, 'Political Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (17, 'Science Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (18, 'Dystopian');
  INSERT INTO public.book_genres (book_id, genre) VALUES (18, 'Philosophy');
  INSERT INTO public.book_genres (book_id, genre) VALUES (18, 'Science Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (3, 'Dark Academia');
  INSERT INTO public.book_genres (book_id, genre) VALUES (19, 'Thriller');
  INSERT INTO public.book_genres (book_id, genre) VALUES (19, 'Literary Fiction');
  INSERT INTO public.book_genres (book_id, genre) VALUES (19, 'Mystery');
  INSERT INTO public.book_genres (book_id, genre) VALUES (19, 'Dark Academia');
  PERFORM pg_catalog.setval('public.books_id_seq', 19, true);
END
$seed$;
