-- Seed users, roles, reviews (+ moods/tags/warnings/helpfuls), and reading statuses.
-- Skips when users already exist (protects existing local DBs).
-- Avatar paths use classpath static /images/avatars/... so clones do not need uploads/.

DO $seed$
BEGIN
  IF EXISTS (SELECT 1 FROM public.users LIMIT 1) THEN
    RAISE NOTICE 'Skipping V3 user/review seed: users table is not empty';
    RETURN;
  END IF;

  INSERT INTO public.users (id, avatar_url, created_at, email, enabled, password, username, about_me, display_name) VALUES (1, NULL, '2026-04-14 21:11:50.867002', 'test@example.com', true, '$2a$10$y8Uf4c/w32kNr2dnaaZsYuT6hZFDmSbfLoQDqjDaAEzNksp5zSfAO', 'testreader', NULL, NULL);
  INSERT INTO public.users (id, avatar_url, created_at, email, enabled, password, username, about_me, display_name) VALUES (4, NULL, '2026-04-18 20:31:49.368423', 'natalia@example.com', true, '$2a$10$9faIupPBPsXPbhaekyRCFu16hqS9FfSZll6Ly/sMnv.PXXqBabodu', 'natalia', NULL, NULL);
  INSERT INTO public.users (id, avatar_url, created_at, email, enabled, password, username, about_me, display_name) VALUES (5, NULL, '2026-04-23 10:23:02.18659', 'arturnskol05@gmail.com', true, '$2a$10$qPVsoPqLc2vmY.8AzabEieD9RS98D2U.1AX5CkNhScOJ32016ym2i', 'Artur', NULL, NULL);
  INSERT INTO public.users (id, avatar_url, created_at, email, enabled, password, username, about_me, display_name) VALUES (6, '/images/avatars/berkobobus.jpg', '2026-09-07 20:59:37.789965', 'b@gmail.com', true, '$2a$10$P7TVhEUen.fbMameNZekrOpGw6VKGjD1EtyvRsOCjdtmrCrsirhzy', 'Berkobobus', NULL, NULL);
  INSERT INTO public.users (id, avatar_url, created_at, email, enabled, password, username, about_me, display_name) VALUES (7, NULL, '2026-09-10 21:07:10.688327', 'clubtest9d16da79@ex.com', true, '$2a$10$B.Dnwqqm//2r./BNPjgZoOLAzMAV3bHpM4abMUFsjErFbebnQkTBq', 'clubtest9d16da79', NULL, NULL);
  INSERT INTO public.users (id, avatar_url, created_at, email, enabled, password, username, about_me, display_name) VALUES (8, NULL, '2026-09-10 21:07:33.14787', 'clubtest6dc686d5@ex.com', true, '$2a$10$mHtnu/qIhhgVEmMol05O3Oc3A/my8XjlzPx0ceX1elPkxJQDzuEzm', 'clubtest6dc686d5', NULL, NULL);
  INSERT INTO public.users (id, avatar_url, created_at, email, enabled, password, username, about_me, display_name) VALUES (9, NULL, '2026-09-10 21:09:04.113505', 'clubokac190c2b@ex.com', true, '$2a$10$3aO8h57h4aXuXQYsAhC0AOx.F9oyOK1EfaCRLIB.5vuMJA2I1Vpay', 'clubokac190c2b', NULL, NULL);
  INSERT INTO public.users (id, avatar_url, created_at, email, enabled, password, username, about_me, display_name) VALUES (3, '/images/avatars/artem.jpg', '2026-04-18 20:22:44.665888', 'artem@example.com', true, '$2a$10$Ck/cP1dZiGglrfF3K6kOt.pWP76quvJ1tKWMFPlm6IgGzSP9fyw8e', 'artem', '', NULL);
  INSERT INTO public.users (id, avatar_url, created_at, email, enabled, password, username, about_me, display_name) VALUES (2, '/images/avatars/karina.jpg', '2026-04-18 20:11:53.744756', 'karina@example.com', true, '$2a$10$ITeo8xBI8Oq1JAFRLrzMQuIsWjdWQ0.XpdXIHDOB6PcjCyddluCy.', 'karina', 'I am a dev of this app and literature enjoyer', 'Karina Skoliboh');
  INSERT INTO public.user_roles (user_id, role) VALUES (1, 'USER');
  INSERT INTO public.user_roles (user_id, role) VALUES (2, 'USER');
  INSERT INTO public.user_roles (user_id, role) VALUES (3, 'USER');
  INSERT INTO public.user_roles (user_id, role) VALUES (4, 'USER');
  INSERT INTO public.user_roles (user_id, role) VALUES (5, 'USER');
  INSERT INTO public.user_roles (user_id, role) VALUES (6, 'USER');
  INSERT INTO public.user_roles (user_id, role) VALUES (7, 'USER');
  INSERT INTO public.user_roles (user_id, role) VALUES (8, 'USER');
  INSERT INTO public.user_roles (user_id, role) VALUES (9, 'USER');
  INSERT INTO public.user_social_links (user_id, url, link_order) VALUES (2, 'https://instagram.com/', 0);
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (1, 2, '2026-04-15 20:49:09.790908', 'Tartt masterfully inverts the detective genre by revealing the murder on the first page, then spends the rest of the novel exploring the psychological aftermath. The prose is lush and intoxicating, much like the world it describes.', true, 0, 'MEDIUM', 5, 'The central event—Bunny''s murder—happens early, but the real suspense lies in watching the group unravel under the weight of their secret. The climax at the ravine and the final dissolution of the clique are particularly haunting.', '2026-04-15 20:49:09.790908', 1, 'A mesmerizing descent into obsession, beauty, and moral decay.', 'Lovers of dark academia, psychological thrillers, and character-driven literary fiction. If you enjoy morally ambiguous protagonists and immersive, slow-burn tension.', 'Readers seeking a fast-paced whodunit or clear-cut heroes. The characters are deeply flawed and often unlikable; the narrative is dense and introspective.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (4, 3, '2026-04-18 20:12:21.011391', 'Tartt masterfully inverts the detective genre by revealing the murder on the first page, then spends the rest of the novel exploring the psychological aftermath. The prose is lush and intoxicating, much like the world it describes.', true, 0, 'MEDIUM', 5, 'The central event—Bunny''s murder—happens early, but the real suspense lies in watching the group unravel under the weight of their secret. The climax at the ravine and the final dissolution of the clique are particularly haunting.', '2026-04-18 20:12:21.011391', 2, 'A mesmerizing descent into obsession, beauty, and moral decay.', 'Lovers of dark academia, psychological thrillers, and character-driven literary fiction. If you enjoy morally ambiguous protagonists and immersive, slow-burn tension.', 'Readers seeking a fast-paced whodunit or clear-cut heroes. The characters are deeply flawed and often unlikable; the narrative is dense and introspective.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (6, 4, '2026-04-18 20:26:08.072563', 'Bradbury distills an entire childhood summer into a series of interconnected vignettes, each one shimmering with wonder and melancholy. From the ritual of bottling dandelion wine to the terror of the Lonely One, every moment captures the heightened awareness of a boy discovering that joy and sorrow are two sides of the same coin. The prose is lyrical without being precious, and the Green Town setting feels both universal and deeply personal.', true, 0, 'MEDIUM', 5, 'The passing of Great-grandma, the revelation of the Lonely One''s true identity, and Douglas''s near-fatal illness all serve as poignant reminders that life''s sweetness is inseparable from its brevity.', '2026-04-18 20:26:08.072563', 3, 'A luminous, bittersweet celebration of summer, memory, and the fragile magic of being alive.', 'Anyone who has ever cherished a summer memory, smelled fresh-cut grass, or felt the pang of time passing. Perfect for readers seeking gentle, poetic fiction that finds the extraordinary in the ordinary.', 'Those who prefer plot-driven narratives or action-packed stories. This is a quiet, reflective book where the biggest event is often a new pair of tennis shoes or the purchase of a trolley ticket.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (7, 4, '2026-04-18 20:32:06.826737', 'Bradbury distills an entire childhood summer into a series of interconnected vignettes, each one shimmering with wonder and melancholy. From the ritual of bottling dandelion wine to the terror of the Lonely One, every moment captures the heightened awareness of a boy discovering that joy and sorrow are two sides of the same coin. The prose is lyrical without being precious, and the Green Town setting feels both universal and deeply personal.', true, 0, 'MEDIUM', 5, 'The passing of Great-grandma, the revelation of the Lonely One''s true identity, and Douglas''s near-fatal illness all serve as poignant reminders that life''s sweetness is inseparable from its brevity.', '2026-04-18 20:32:06.826737', 4, 'A luminous, bittersweet celebration of summer, memory, and the fragile magic of being alive.', 'Anyone who has ever cherished a summer memory, smelled fresh-cut grass, or felt the pang of time passing. Perfect for readers seeking gentle, poetic fiction that finds the extraordinary in the ordinary.', 'Those who prefer plot-driven narratives or action-packed stories. This is a quiet, reflective book where the biggest event is often a new pair of tennis shoes or the purchase of a trolley ticket.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (8, 5, '2026-04-18 20:34:43.25253', 'Tevis writes about chess with the precision and tension of a thriller. Beth Harmon is an unforgettable protagonist—gifted, damaged, and fiercely determined. The novel never glamorizes her addictions; instead, it shows how her genius and her demons are intertwined. The prose is spare and exact, mirroring the game itself, and the supporting cast—from the stoic janitor Mr. Shaibel to the enigmatic Benny Watts—adds depth without distracting from Beth''s solitary journey.', true, 0, 'MEDIUM', 4, 'Beth''s final match against Borgov in Moscow, her triumph without the aid of tranquilizers, and the quiet, redemptive return to the orphanage to honor Mr. Shaibel are the emotional climaxes of the story.', '2026-04-18 20:34:43.25253', 4, 'A taut, elegant novel about chess, compulsion, and the price of brilliance.', 'Fans of character-driven stories about obsession and mastery. You don''t need to know chess—the novel explains just enough to make the matches thrilling. Perfect for readers who enjoyed *The Goldfinch* or *A Beautiful Mind*.', 'Those seeking light entertainment or a romance subplot. The focus is squarely on Beth''s internal struggles and the chess world; relationships are secondary and often strained.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (10, 4, '2026-04-23 12:31:23.652347', 'Bradbury’s prose is undeniably gorgeous — whole paragraphs read like poetry — and his ability to infuse everyday rituals with wonder is unmatched. The high points (the Happiness Machine, Mrs. Bentley’s lost letters) are profoundly moving. However, the episodic, almost plotless construction sometimes leaves the narrative feeling weightless; a few chapters read more like isolated sketches than parts of a cohesive whole. It’s a book to admire as much as to love, and its emotional resonance will depend entirely on your willingness to sink into its unhurried, reflective rhythm.', true, 0, 'SLOW', 4, 'Key episodes include the defeat of the ''Lonely One,'' the heartbreaking realization of the older woman that she has outlived her era, and the final bottling of summer itself. These moments shine brightest, though they are interspersed with more forgettable vignettes.', '2026-04-23 12:31:23.652347', 2, 'An exquisitely written, fragmentary portrait of a Midwestern summer that occasionally drifts too far into reverie.', 'Readers who value atmosphere and language over plot. Those with a fondness for memory pieces, Ray Bradbury’s softer side, or literary nostalgia. A great match for someone looking to savor each sentence.', 'Plot-driven readers, or those who become impatient with stories that prioritize mood over momentum. Some may find the lack of central conflict and the rose-tinted nostalgia a bit cloying after a while.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (11, 8, '2026-04-23 15:00:41.394843', 'Shelley’s debut is nothing short of astonishing in its ambition and prescience. The central conceit—a man playing God and recoiling from his creation—raises timeless questions about responsibility, empathy, and what makes a monster. The creature’s first-person narrative is the novel’s heart, eloquent and devastating in its loneliness. Victor Frankenstein himself can be a frustratingly passive protagonist, wallowing in guilt rather than acting. Still, the icy dread of the final chase and the philosophical weight of the novel’s central tragedy make it an essential read, even if the emotional impact is sometimes blunted by the distance imposed by its structure.', false, 0, 'SLOW', 4, NULL, '2026-04-23 15:00:41.394843', 2, 'A revolutionary novel of ideas that gave birth to science fiction and remains deeply unsettling, though its sometimes overwrought prose distance the reader from its emotional core.', 'Lovers of classic literature, foundational science fiction, and Gothic horror. Ideal for those who enjoy grappling with moral ambiguity, the ethics of creation, and the nature of alienation.', 'Those who prefer fast-paced, visceral horror or tightly linear narratives. The 19th-century prose can feel dense, and Victor’s relentless passivity and self-pity may try the patience of readers seeking a more proactive hero.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (12, 6, '2026-04-24 20:24:54.586401', 'R.F. Kuang has crafted something extraordinary—a novel that is at once a love letter to etymology, a searing indictment of colonialism, and a heartbreaking coming-of-age story set in the gilded halls of Oxford''s fictional Institute of Translation. The magic system, in which the nuances of language are harnessed to bend reality, is brilliantly inventive, and the footnotes that cradle the narrative add a scholarly weight that makes the world feel achingly real.', true, 0, 'MEDIUM', 5, 'The silver-working magic system relies on the untranslatable gaps between languages; the climax sees the Oxford tower itself turned into a weapon of mass liberation. The footnotes gradually reveal the deeper conspiracies of the British Empire, and the final sacrifice of Robin Swift is as heartbreaking as it is cathartic.', '2026-04-24 20:24:54.586401', 2, 'A magnificent, rage-filled symphony of language, power, and resistance that redefines dark academia.', 'Lovers of dark academia, linguistic puzzles, and anti-colonial literature. Anyone who values meticulous world-building, morally complex characters, and stories that make you think as much as feel. Perfect for fans of ''The Secret History'' and ''Jonathan Strange & Mr Norrell'', but with a righteous political edge.', 'Those seeking light escapism or fast-paced action. The novel is deliberately dense, scholarly, and builds toward a violent, tragic climax that may be too heavy for some. If you dislike extensive footnotes or stories where systemic injustice takes center stage, this might not be your cup of tea.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (9, 3, NULL, 'Tartt masterfully inverts the detective genre by revealing the murder on the first page, then spends the rest of the novel exploring the psychological aftermath. The prose is lush and intoxicating, much like the world it describes.', true, 1, 'MEDIUM', 5, 'The central event—Bunny''s murder—happens early, but the real suspense lies in watching the group unravel under the weight of their secret. The climax at the ravine and the final dissolution of the clique are particularly haunting.', '2026-09-20 19:24:21.693614', 3, 'A mesmerizing descent into obsession, beauty, and moral decay.', 'Lovers of dark academia, psychological thrillers, and character-driven literary fiction. If you enjoy morally ambiguous protagonists and immersive, slow-burn tension.', 'Readers seeking a fast-paced whodunit or clear-cut heroes. The characters are deeply flawed and often unlikable; the narrative is dense and introspective.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (3, 3, NULL, 'Tartt masterfully inverts the detective genre by revealing the murder on the first page, then spends the rest of the novel exploring the psychological aftermath. The prose is lush and intoxicating, much like the world it describes.', true, 1, 'MEDIUM', 5, 'The central event—Bunny''s murder—happens early, but the real suspense lies in watching the group unravel under the weight of their secret. The climax at the ravine and the final dissolution of the clique are particularly haunting.', '2026-09-20 19:24:35.163141', 1, 'A mesmerizing descent into obsession, beauty, and moral decay.', 'Lovers of dark academia, psychological thrillers, and character-driven literary fiction. If you enjoy morally ambiguous protagonists and immersive, slow-burn tension.', 'Readers seeking a fast-paced whodunit or clear-cut heroes. The characters are deeply flawed and often unlikable; the narrative is dense and introspective.');
  INSERT INTO public.reviews (id, book_id, created_at, detailed_review, has_spoiler, helpful_count, pacing, rating, spoiler_content, updated_at, user_id, verdict, who_is_it_for, who_is_it_not_for) VALUES (13, 19, NULL, 'M.L. Rio’s debut is a masterclass in atmosphere. It follows seven fourth-year theatre students at an elite conservatory, all typecast in their usual roles - both on stage and off. The narrative is framed as a confession from Oliver Marks to the detective who put him in prison a decade earlier, drawing the reader into a web of loyalty, jealousy, and a murder that may or may not have been an accident.
  The book''s greatest strength is its seamless fusion of Shakespearean tragedy with the claustrophobic intensity of a friend group. The students quote the Bard in casual conversation, using his lines to justify their flaws and escalate their rivalries. The drama of Julius Caesar bleeds into their real lives, and the result is a slow, inevitable descent into madness and violence. The characters are deeply flawed and often theatrical to the point of frustration, but that is precisely the point - they are performers who have forgotten how to be anything else.
  The prose is lush and evocative, capturing the gothic, autumnal atmosphere of the conservatory and the creeping dread of a guilt that can never be truly shared. The middle section sags slightly as the narrative juggles its timelines, but the final act is a relentless, heartbreaking crescendo. The ending will stay with you long after you turn the last page - it is quiet, ambiguous, and utterly devastating.', true, 0, 'FAST', 5, 'The central mystery (who killed Richard) unfolds with the logic of a Shakespearean tragedy. The revelation that James delivered the fatal blow, and that Oliver helped cover it up, is less of a twist and more of an inevitability. The novel’s true power lies not in the whodunit but in the psychological aftermath. The final chapter, set ten years later, reveals that James has died by suicide, leaving Oliver alone to grapple with their shared secret and the love they never fully articulated. The queer subtext between Oliver and James is one of the novel’s most poignant threads, and its tragic resolution underlines the book’s core theme: that the roles we are assigned - by others and by ourselves - can become our prisons.', '2026-09-20 21:10:50.042258', 3, 'A gorgeously written, atmospheric tragedy about seven Shakespearean actors whose insular world implodes after a murder. It''s a slow-burn meditation on obsession, guilt, and the stories we tell to survive.', 'Readers who love dark academia, slow burns, rich worlds, and quiet, devastating endings. This is for anyone who ever lost themselves in a play, a friendship, or a story so completely that the lines between art and life began to blur.', 'Anyone looking for a quick, light beach read. Also, be wary if you dislike Shakespeare - the novel is saturated with his words, and the characters frequently speak in his quotes. Readers who need fast-paced, plot-driven action may find the pacing uneven.');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (1, 'Animal death');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (1, 'Incestuous undertones');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (1, 'Substance abuse');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (1, 'Murder');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (1, 'Suicide');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (3, 'Animal death');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (3, 'Incestuous undertones');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (3, 'Substance abuse');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (3, 'Murder');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (3, 'Suicide');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (4, 'Animal death');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (4, 'Incestuous undertones');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (4, 'Substance abuse');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (4, 'Murder');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (4, 'Suicide');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (6, 'Death of a loved one');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (6, 'Brief mentions of aging and mortality');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (6, 'Mild horror elements (the Lonely One)');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (7, 'Death of a loved one');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (7, 'Brief mentions of aging and mortality');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (7, 'Mild horror elements (the Lonely One)');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (8, 'Brief mention of suicide');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (8, 'Child neglect');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (8, 'Addiction (alcohol, tranquilizers)');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (8, 'Emotional abuse');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (9, 'Animal death');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (9, 'Incestuous undertones');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (9, 'Substance abuse');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (9, 'Murder');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (9, 'Suicide');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (10, 'Very mild; brief mentions of death and aging are handled with a gentle touch');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (11, 'Grief/Loss');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (12, 'Grief/Loss');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (12, 'Violence');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (12, 'Racism');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (13, 'Eating Disorders');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (13, 'Substance Use');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (13, 'Grief/Loss');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (13, 'Mental Illness');
  INSERT INTO public.review_content_warnings (review_id, warning) VALUES (13, 'Violence');
  INSERT INTO public.review_helpfuls (id, created_at, review_id, user_id) VALUES (1, '2026-09-20 19:24:21.61728', 9, 2);
  INSERT INTO public.review_helpfuls (id, created_at, review_id, user_id) VALUES (2, '2026-09-20 19:24:35.156607', 3, 2);
  INSERT INTO public.review_moods (review_id, mood) VALUES (1, 'Tense');
  INSERT INTO public.review_moods (review_id, mood) VALUES (1, 'Dark');
  INSERT INTO public.review_moods (review_id, mood) VALUES (1, 'Philosophical');
  INSERT INTO public.review_moods (review_id, mood) VALUES (1, 'Atmospheric');
  INSERT INTO public.review_moods (review_id, mood) VALUES (3, 'Tense');
  INSERT INTO public.review_moods (review_id, mood) VALUES (3, 'Dark');
  INSERT INTO public.review_moods (review_id, mood) VALUES (3, 'Philosophical');
  INSERT INTO public.review_moods (review_id, mood) VALUES (3, 'Atmospheric');
  INSERT INTO public.review_moods (review_id, mood) VALUES (4, 'Tense');
  INSERT INTO public.review_moods (review_id, mood) VALUES (4, 'Dark');
  INSERT INTO public.review_moods (review_id, mood) VALUES (4, 'Philosophical');
  INSERT INTO public.review_moods (review_id, mood) VALUES (4, 'Atmospheric');
  INSERT INTO public.review_moods (review_id, mood) VALUES (6, 'Nostalgic');
  INSERT INTO public.review_moods (review_id, mood) VALUES (6, 'Whimsical');
  INSERT INTO public.review_moods (review_id, mood) VALUES (6, 'Bittersweet');
  INSERT INTO public.review_moods (review_id, mood) VALUES (6, 'Philosophical');
  INSERT INTO public.review_moods (review_id, mood) VALUES (7, 'Nostalgic');
  INSERT INTO public.review_moods (review_id, mood) VALUES (7, 'Whimsical');
  INSERT INTO public.review_moods (review_id, mood) VALUES (7, 'Bittersweet');
  INSERT INTO public.review_moods (review_id, mood) VALUES (7, 'Philosophical');
  INSERT INTO public.review_moods (review_id, mood) VALUES (8, 'Tense');
  INSERT INTO public.review_moods (review_id, mood) VALUES (8, 'Melancholic');
  INSERT INTO public.review_moods (review_id, mood) VALUES (8, 'Introspective');
  INSERT INTO public.review_moods (review_id, mood) VALUES (8, 'Triumphant');
  INSERT INTO public.review_moods (review_id, mood) VALUES (9, 'Tense');
  INSERT INTO public.review_moods (review_id, mood) VALUES (9, 'Dark');
  INSERT INTO public.review_moods (review_id, mood) VALUES (9, 'Philosophical');
  INSERT INTO public.review_moods (review_id, mood) VALUES (9, 'Atmospheric');
  INSERT INTO public.review_moods (review_id, mood) VALUES (10, 'Nostalgic');
  INSERT INTO public.review_moods (review_id, mood) VALUES (10, 'Reflective');
  INSERT INTO public.review_moods (review_id, mood) VALUES (10, 'Sentimental');
  INSERT INTO public.review_moods (review_id, mood) VALUES (10, 'Wistful');
  INSERT INTO public.review_moods (review_id, mood) VALUES (11, 'HEARTBREAKING');
  INSERT INTO public.review_moods (review_id, mood) VALUES (11, 'SOMBER');
  INSERT INTO public.review_moods (review_id, mood) VALUES (11, 'TENSE');
  INSERT INTO public.review_moods (review_id, mood) VALUES (12, 'INSPIRING');
  INSERT INTO public.review_moods (review_id, mood) VALUES (12, 'WHIMSICAL');
  INSERT INTO public.review_moods (review_id, mood) VALUES (12, 'HOPEFUL');
  INSERT INTO public.review_moods (review_id, mood) VALUES (13, 'HEARTBREAKING');
  INSERT INTO public.review_moods (review_id, mood) VALUES (13, 'SOMBER');
  INSERT INTO public.review_moods (review_id, mood) VALUES (13, 'MELANCHOLIC');
  INSERT INTO public.review_moods (review_id, mood) VALUES (13, 'DARK');
  INSERT INTO public.review_tags (review_id, tag) VALUES (1, 'greek-tragedy');
  INSERT INTO public.review_tags (review_id, tag) VALUES (1, 'unreliable-narrator');
  INSERT INTO public.review_tags (review_id, tag) VALUES (1, 'literary-fiction');
  INSERT INTO public.review_tags (review_id, tag) VALUES (1, 'dark-academia');
  INSERT INTO public.review_tags (review_id, tag) VALUES (3, 'greek-tragedy');
  INSERT INTO public.review_tags (review_id, tag) VALUES (3, 'unreliable-narrator');
  INSERT INTO public.review_tags (review_id, tag) VALUES (3, 'literary-fiction');
  INSERT INTO public.review_tags (review_id, tag) VALUES (3, 'dark-academia');
  INSERT INTO public.review_tags (review_id, tag) VALUES (4, 'greek-tragedy');
  INSERT INTO public.review_tags (review_id, tag) VALUES (4, 'unreliable-narrator');
  INSERT INTO public.review_tags (review_id, tag) VALUES (4, 'literary-fiction');
  INSERT INTO public.review_tags (review_id, tag) VALUES (4, 'dark-academia');
  INSERT INTO public.review_tags (review_id, tag) VALUES (6, 'nostalgia');
  INSERT INTO public.review_tags (review_id, tag) VALUES (6, 'small-town');
  INSERT INTO public.review_tags (review_id, tag) VALUES (6, 'summer-read');
  INSERT INTO public.review_tags (review_id, tag) VALUES (6, 'magical-realism');
  INSERT INTO public.review_tags (review_id, tag) VALUES (6, 'coming-of-age');
  INSERT INTO public.review_tags (review_id, tag) VALUES (7, 'nostalgia');
  INSERT INTO public.review_tags (review_id, tag) VALUES (7, 'small-town');
  INSERT INTO public.review_tags (review_id, tag) VALUES (7, 'summer-read');
  INSERT INTO public.review_tags (review_id, tag) VALUES (7, 'magical-realism');
  INSERT INTO public.review_tags (review_id, tag) VALUES (7, 'coming-of-age');
  INSERT INTO public.review_tags (review_id, tag) VALUES (8, 'genius');
  INSERT INTO public.review_tags (review_id, tag) VALUES (8, 'chess');
  INSERT INTO public.review_tags (review_id, tag) VALUES (8, 'addiction');
  INSERT INTO public.review_tags (review_id, tag) VALUES (8, 'feminist-icon');
  INSERT INTO public.review_tags (review_id, tag) VALUES (8, '1960s');
  INSERT INTO public.review_tags (review_id, tag) VALUES (8, 'coming-of-age');
  INSERT INTO public.review_tags (review_id, tag) VALUES (9, 'greek-tragedy');
  INSERT INTO public.review_tags (review_id, tag) VALUES (9, 'unreliable-narrator');
  INSERT INTO public.review_tags (review_id, tag) VALUES (9, 'literary-fiction');
  INSERT INTO public.review_tags (review_id, tag) VALUES (9, 'dark-academia');
  INSERT INTO public.review_tags (review_id, tag) VALUES (10, 'nostalgia');
  INSERT INTO public.review_tags (review_id, tag) VALUES (10, 'slice-of-life');
  INSERT INTO public.review_tags (review_id, tag) VALUES (10, 'lyrical-prose');
  INSERT INTO public.review_tags (review_id, tag) VALUES (10, 'quiet-novel');
  INSERT INTO public.review_tags (review_id, tag) VALUES (10, 'literary-fiction');
  INSERT INTO public.review_tags (review_id, tag) VALUES (10, 'coming-of-age');
  INSERT INTO public.review_tags (review_id, tag) VALUES (11, 'HEARTBREAKING');
  INSERT INTO public.review_tags (review_id, tag) VALUES (11, 'SOMBER');
  INSERT INTO public.review_tags (review_id, tag) VALUES (11, 'TENSE');
  INSERT INTO public.review_tags (review_id, tag) VALUES (12, 'INSPIRING');
  INSERT INTO public.review_tags (review_id, tag) VALUES (12, 'WHIMSICAL');
  INSERT INTO public.review_tags (review_id, tag) VALUES (12, 'HOPEFUL');
  INSERT INTO public.review_tags (review_id, tag) VALUES (13, 'HEARTBREAKING');
  INSERT INTO public.review_tags (review_id, tag) VALUES (13, 'SOMBER');
  INSERT INTO public.review_tags (review_id, tag) VALUES (13, 'MELANCHOLIC');
  INSERT INTO public.review_tags (review_id, tag) VALUES (13, 'DARK');
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (13, 3, 'READING', '2026-04-23 10:13:14.158749', 3);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (2, 4, 'READ', '2026-04-24 20:10:53.919123', 2);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (11, 6, 'READ', '2026-04-24 20:24:54.441535', 2);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (16, 4, 'WANT_TO_READ', '2026-04-28 17:53:27.954853', 4);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (17, 7, 'READING', '2026-04-28 17:53:39.712662', 4);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (19, 13, 'WANT_TO_READ', '2026-09-07 21:03:21.417387', 3);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (21, 8, 'ABANDONED', '2026-09-16 18:49:47.294831', 4);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (7, 3, 'READING', '2026-09-18 22:10:32.671836', 2);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (22, 5, 'READ', '2026-09-18 22:15:44.12702', 4);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (20, 5, 'WANT_TO_READ', '2026-09-18 22:16:18.145295', 2);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (23, 19, 'READ', '2026-09-20 20:29:22.278114', 3);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (24, 19, 'READING', '2026-09-21 16:21:01.886979', 2);
  INSERT INTO public.user_book_status (id, book_id, status, updated_at, user_id) VALUES (15, 8, 'READ', '2026-09-21 16:21:45.621955', 2);
  PERFORM pg_catalog.setval('public.users_id_seq', 9, true);
  PERFORM pg_catalog.setval('public.reviews_id_seq', 13, true);
  PERFORM pg_catalog.setval('public.review_helpfuls_id_seq', 2, true);
  PERFORM pg_catalog.setval('public.user_book_status_id_seq', 24, true);
END
$seed$;
